global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "student-management"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["192.168.49.2:30080"]

  - job_name: "jenkins"
    metrics_path: /prometheus
    static_configs:
      - targets: ["localhost:8080"]
