apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-management
  namespace: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-management
        image: student-management:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_JPA_SHOW_SQL
        livenessProbe:
          httpGet:
            path: /students
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /students
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
