apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
  SPRING_JPA_SHOW_SQL: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: "/actuator"
