apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops
type: Opaque
data:
  # root password: rootpassword (base64 encoded)
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # database password: studentpass (base64 encoded)
  mysql-password: c3R1ZGVudHBhc3M=
